### ISSUE TITLE
Conflicting directions pertaining to Known Limitations & Configuration Requirements

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/ontap-sanhost#104]
Page: [NVMe/FC Host Configuration for Oracle Linux 8.6 with ONTAP](https://docs.netapp.com/us-en/ontap-sanhost/nvme_ol_86.html)

First bullet in the "Known Limitations" states: NVME/TCP is a technology preview feature and hence the support is not posted on Interoperability Matrix Tool

Then we state under Configuration Requirements: Refer to the [NetApp Interoperability Matrix](https://mysupport.netapp.com/matrix/) for exact details regarding supported configurations.

Seems the first bullet under known limitations is incorrect since we are referring the customer to the IMT to get the details on the supported configuration (and NVMe/TCP is listed in the IMT).

**Comment by netapp-ranuk** [comment]
Thanks for your comment. We'll get back soon.

**Comment by netapp-ranuk** [comment]
Hi @DrKeno,
To use any protocol in a SAN environment, the protocol must be supported by both ONTAP and the specific host.  NVMe/TCP is supported in ONTAP beginning with ONTAP 9.10.1.  However, Oracle Linux 8.6 support of NVMe/TCP is still in the preview phase,  meaning it is in the process of being fully qualified.  We’ve decided to remove the OL 8.6 documentation until it is fully qualified.  

 Thank you for your feedback.
