### ISSUE TITLE
Misleading information on this page

### ISSUE THREAD

**Issue by m-worthen** [NetAppDocs/ontap-sanhost#113]
Page: [NVMe-oF Host Configuration for ESXi 7.x with ONTAP](https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_7.html)

The first bullet point on this page states the following:
"NVMe over Fibre Channel (NVMe/FC) is supported on ONTAP 9.7 or later."

Which may lead readers to believe NVMe/FC wasn't supported until 9.7 or later (which isn't true as it was first introduced in 9.4). I believe what the authors of the page are trying to convey is VMware and NVMe/FC aren't supported together until ONTAP 9.7 and VMware 7.U3

**Comment by netapp-ranuk** [comment]
Thank you for the feedback. We will get back soon.

**Comment by netapp-ranuk** [comment]
We have now revised the sentence in the VSphere 7 document. https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_7.html.
