### ISSUE TITLE
Found a typo on this page

### ISSUE THREAD

**Issue by liamp-sys** [NetAppDocs/ontap-sanhost#114]
Page: [Using IBM AIX 7.2 and/or PowerVM (VIOS 3.1) with NetApp ONTAP](https://docs.netapp.com/us-en/ontap-sanhost/hu_aix_72.html)

The item "re_timeout (disk)" in the Recommended Settings section/table should be "rw_timeout (disk)".

**Comment by netapp-ranuk** [comment]
Thank you for your feedback. We will resolve the issue soon.

**Comment by netapp-ranuk** [comment]
We have corrected the typo in the parameter. https://docs.netapp.com/us-en/ontap-sanhost/hu_aix_72.html#recommended-settings. Thank you for highlighting this.
