### ISSUE TITLE
Clarification on the HUK Install for 6.2

### ISSUE THREAD

**Issue by ianvoss** [NetAppDocs/ontap-sanhost#120]
Page: [Using Solaris 11.4 with NetApp ONTAP](https://docs.netapp.com/us-en/ontap-sanhost/hu_solaris_114.html)

A customer has had some issues with the Install guide for the 6.2 HUK not being as Verbose as the 6.1 (showing an example of the install and where it places/modifies files). The following is a more "complete" issue description.

"Customer's issue was that during the install of the Solaris 6.2 HUK for Solaris 11.4, the documentation does not give an example of Where the values are changed.
Customer showed me that in the 6.1 installation guide(https://library.netapp.com/ecm/ecm_download_file/ECMP1148981), there was an example that showed it editing the /kernel/drv/ssd.conf file but when the 6.2 install is ran, it makes changes somewhere in /etc/ssd.conf
Customer believes this to possibly be the wrong location that Solaris will reference for it's values.

In https://docs.netapp.com/us-en/ontap-sanhost/hu_solaris_114.html#known-problems-and-limitations
The first line documents making a change (putting the values edited from the HUK into the sd.conf instead of ssd.conf) but if the HUK is installing it in the wrong place then it is Not documented to look in /etc/ssd.conf.
"

He also requested that the following be included in this one document instead of having to search around multiple different places when it should all be in one guide:

An1: Five things are necessary for successful 4KB aligned IO for zpools using NETAPP LUN Filer:

1) First, you must ensure you are running a sufficiently current Solaris to ensure that all Solaris features supporting 4KB IO size/alignment are in place. Solaris 10 update 11 (the latest) suffices.

2) The NETAPP logical unit/volume must be of lun/host-type "Solaris" regardless of size of LUN. Do not use lun/host-type "Solaris-EFI". Solaris_EFI will lead to misaligned IO even when ZFS is generating 4KB aligned IO (ashift 12). Earlier NETAPP documentation recommended Solaris_EFI for disks over a certain size (1.5TB). That advice is now obsolete.  See NETAPP Host Utilities 6.x for further information.

3) The Solaris 10 SPARC /kernel/drv/ssd.conf or Solaris 11 SPARC /etc/driver/drv/ssd.conf file must have an ssd-config-list entry similar to this:
ssd-config-list="NETAPP LUN", "cache-nonvolatile:true, disksort:false, physical-block-size:4096, retries-busy:30, retries-reset:30, retries-notready:300, retries-timeout:10, throttle-max:64, throttle-min:8";
 
NOTE: Upgraded Solaris 11 SPARC systems will continue to bind to the ssd driver, but a fresh installation of Solaris 11.4 on a SPARC system will result in Fibre Channel devices binding to the sd driver. Use of inception points can override this behavior.
Reference the following document for more information:
ZFS And NETAPP LUN 4KB I/O Misalignment (Doc ID 1585893.1)

**Comment by netapp-ehoffman** [comment]
@ianvoss, Thank you for taking the time to provide this really helpful feedback. We'll begin reviewing/discussion with SMEs as soon as possible.

**Comment by netapp-ranuk** [comment]
Thank you for your input. We have reached out to the SMEs regarding this feedback.

**Comment by netapp-ranuk** [comment]
In progress @netapp-chandaj. Expect to close this soon.

**Comment by netapp-ranuk** [comment]
Hi @ianvoss 

We discussed internally with the engineers and have added recommendations here https://docs.netapp.com/us-en/ontap-sanhost/hu_solaris_114.html#recommended-settings as per the advice.

Hope this resolves the issue. Please let us know if you've any other concerns.
