### ISSUE TITLE
link target for santricity

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/ontap-sanhost#127]
Page: [Windows Unified Host Utilities Release Notes](https://docs.netapp.com/us-en/ontap-sanhost/hu_wuhu_71_rn.html)

The link at the bottom:

> See the [E-Series documentation](https://docs.netapp.com/us-en/e-series/getting-started/index.html) to find SANtricity related documentation.

Why not link to the [SANtricity docs](https://docs.netapp.com/us-en/e-series-santricity/index.html) or the [E-Series family](https://docs.netapp.com/us-en/e-series-family/)?

**Comment by netapp-ranuk** [comment]
Thanks, Megan. I'll get back on this soon.

**Comment by netapp-ranuk** [comment]
We have updated the link to point to the E-Series family page. Thank you!
