### ISSUE TITLE
What is the logic that informs the sidebar order, the order of the tiles, and the order within the tiles?

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap-sanhost#129]
Page: [SAN hosts and cloud clients](https://docs.netapp.com/us-en/ontap-sanhost/index.html)

In this doc site's sidebar, the NvME-oF host configurations node is above the FCP and iSCSI host configurations node. Is there a reason for this? If so, why does the left-to-right order of the corresponding tiles on the site's home page not reflect the same order? Left-to-right, the tiles are in the opposite order as the sidebar. There also seems to be no intent in the way we organize the subsections in the sidebar and tiles? Are we using alphabetical by height? Phases of the moon? Surely we can do better.

I also see no reason why the various topics inside the SAN host utilities node don't all start with Release notes instead of the Install topic. Shouldn't release notes appear first?

**Comment by netapp-pcarriga** [comment]
Hi @adamn-ntap - Thank you for your feedback. We are reviewing this valuable input and will update the documentation as soon as possible.

**Comment by netapp-pcarriga** [comment]
Hi @adamn-ntap - We've restructured the landing page and sidebar. The protocols are now in alphabetical order in both locations. Also, within the sidebar subsections, the topics now start with release notes.
