### ISSUE TITLE
Link to Notice file is broken. And is it even needed?

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap-sanhost#131]
The "Notice File" link (yellow highlight in the screencap below) is broken. See the message I get in the second screencap in this issue.

![image](https://user-images.githubusercontent.com/36739591/235998557-f004f9de-986f-4346-856f-c14aed9ae0b5.png)

Also, do we even need this link? It appears that the Legal notices section is pointing to some kind of Notices file also.

![image](https://user-images.githubusercontent.com/36739591/235998944-35fc06cc-9d16-41b1-afb5-70f9aaf79516.png)

**Comment by netapp-pcarriga** [comment]
Hi @adamn-ntap - Thank you for your feedback. We are reviewing this valuable input and will update the documentation as soon as possible.

**Comment by ntap-bmegan** [comment]
FYI @adamn-ntap & @netapp-pcarriga - This was a requirement from Legal. The link should immediately open the Notice PDF (or multiple links for products where multiple Notice PDFs apply.) The general approach was most recently revalidated with Legal last summer during some other work in this area.

**Comment by netapp-ranuk** [comment]
Hi @adamn-ntap - We've removed the Notice File link from the Linux guide, please see [here](https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html).
