### ISSUE TITLE
Mongrel topics cover install and command references

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap-sanhost#132]
What is the content architecture that informs delivering topics that cover installation and then also include command references?

In the attached screencap -- which is just one specific instance of a pattern replicated in other topics -- I've highlighted in yellow the section I think should be in a separate file. See the red arrow for recommended placement of the new topic in the left sidebar.

![image](https://user-images.githubusercontent.com/36739591/236000532-3f55b79a-cde1-4019-b98b-4fd799dd339e.png)

**Comment by netapp-pcarriga** [comment]
Hi @adamn-ntap - Thank you for your feedback. We are reviewing this valuable input and will update the documentation as soon as possible.

**Comment by netapp-ranuk** [comment]
Hi @adamn-ntap We've made amendments to the install guides. We have separated out the command references and placed them in separate files as per the recommendation. Please see [here](https://docs.netapp.com/us-en/ontap-sanhost/hu_aix_61_cmd.html).
