### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-sanhost#167]
### Page URL

https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html

### Page title

Using Windows Server 2022 with ONTAP

### Summary

Hi,

Each of the Configuration pages for Windows Host Utilities (2022, 2019, 2016, 2012R2) has a link at the bottom pointing an Installation instruction at library.netapp.com

<img width="876" alt="Screenshot 2023-11-09 at 16 53 38" src="https://github.com/NetAppDocs/ontap-sanhost/assets/2291693/b2cad159-d1ea-4e13-a425-5b1d75bcdd67">

URL: https://library.netapp.com/ecmdocs/ECMLP2789202/html/index.html

So the main issue is that if I try and access, I get a "Not Authorized" error.
But I am also thinking, the link should instead be to the install section of this same documentation set.
Like point to here: 
<img width="429" alt="Screenshot 2023-11-09 at 16 58 08" src="https://github.com/NetAppDocs/ontap-sanhost/assets/2291693/d40c7944-9809-41fc-bbb8-a5dfc6d23c7f">

Not sure if we want to point to 7.1 or the latest, 7.2 though..

Thanks,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
Thanks for reporting the issue. We'll work on this and resolve it as soon as possible.

**Comment by netapp-ranuk** [comment]
Hi @estarz 

We have fixed the broken link. In addition, you can select the installation procedure for your Windows Unified Host Utilities version.
