### ISSUE TITLE
MCS = Multiple connections per **session**

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap-sanhost#168]
### Page URL

https://docs.netapp.com/us-en/ontap-sanhost/hu_wuhu_71_rn.html

### Page title

Windows Unified Host Utilities Release Notes

### Summary

"Multiple connections per second (MCS)"

should be

"Multiple connections per **session** (MCS)"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
Thank you for reporting this. We will correct the issue as soon as possible.

**Comment by netapp-ranuk** [comment]
Hi @SPGoetze we have corrected the issue. Please find the updated document https://docs.netapp.com/us-en/ontap-sanhost/hu_wuhu_71_rn.html#whats-new.

Thank you!
