### ISSUE TITLE
WUHU 7.2 references instead of the old 7.1

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap-sanhost#169]
### Page URL

https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html

### Page title

Using Windows Server 2022 with ONTAP

### Summary

Why not refer to the current **7.2** release of WUHU???
(Multiple pages & places)

"For WUHU configuration information and instructions, please refer to [WUHU 7.1 Documentation](https://docs.netapp.com/us-en/ontap-sanhost/hu_wuhu_71.html)."

This is also present on the 2019/2016/2012 pages
https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2019.html
https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2016.html
https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2012r2.html

Greetings from Zagreb, where I'm teaching a SAN Admin course...

Sebastian

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @SPGoetze, thank you for suggesting this. I will discuss with the ONTAP Select team and update the documentation accordingly.

**Comment by SPGoetze** [comment]
Not ONTAP *Select*, by the way.

Just regular ONTAP *SAN*...

Greetings from Zagreb

Sebastian
(was teaching a SAN course there...)

**Comment by netapp-ranuk** [comment]
Hi @SPGoetze 

We have added a link to the relevant section and you can select the installation procedure for your Windows Unified Host Utilities version and find the necessary information. Please find the link: https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html.
