### ISSUE TITLE
Documentation doesn't tell me "why"

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap-sanhost#180]
### Page URL

https://docs.netapp.com/us-en/ontap-sanhost/overview.html

### Page title

SAN host configuration overview

### Summary

I don't understand whether this documentation is required to configure SAN clients or whether it's optional, but a best practice. In other words, why should I read the contents of this doc site? What problem am I solving by installing the SAN host utilities and configuring my hosts?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
Thanks, Ben for your feedback. We'll review this valuable input and will update the documentation as soon as possible.

**Comment by netapp-ranuk** [comment]
We have revised the overview text

https://docs.netapp.com/us-en/ontap-sanhost/overview.html
