### ISSUE TITLE
Missing information for Ubuntu

### ISSUE THREAD

**Issue by liamp-sys** [NetAppDocs/ontap-sanhost#181]
### Page URL

https://docs.netapp.com/us-en/ontap-sanhost/hu_nvme_index.html

### Page title

Overview

### Summary

Please add configuration info/howto for configuring NVMe-oF for Ubuntu Linux hosts.
The Interoperability Matrix shows that we support Ubuntu with both NVMe/TCP and NVMe/FC protocols.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @liamp-sys, thank you for raising this issue. We will investigate and follow up here.

**Comment by netapp-ranuk** [comment]
Hi @liamp-sys  

We have published the Ubuntu 22.04 docs here:

NVMe https://docs.netapp.com/us-en/ontap-sanhost/nvme_ubuntu_2204.html
FCP https://docs.netapp.com/us-en/ontap-sanhost/hu_ubuntu_2204.html

Thanks!
