### ISSUE TITLE
MetroCluster recommendations 

### ISSUE THREAD

**Issue by Brandon12345678901** [NetAppDocs/ontap-sanhost#187]
### Page URL

https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_7.html

### Page title

Use VMware vSphere 7.x with ONTAP

### Summary

We are seeing outages during MCC switchover / switchback .... can we have more specific MCC recommendations like 120 sec timeouts ?
Thanks 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @Brandon12345678901, thank you for bringing this issue to our attention. I will investigate and update you here.

**Comment by Brandon12345678901** [comment]
Thanks ..additionally any configuration/recommendations  for Cisco / Brocade switch ports would be good seems LIF FLOGI issues cause some init storage login problems

**Comment by netapp-pcarriga** [comment]
Hi @Brandon12345678901, for this particular issue, the recommendation is to log a support case with NetApp so the issue can be explored further. If needed, please contact your NetApp SE for guidance on how to do this.

Thanks again for taking time to open this issue and helping us improve our customer documentation.
