### ISSUE TITLE
Known issue that system fails to boot when adding an NVMe-FC device as a mount point in /etc/fstab

### ISSUE THREAD

**Issue by kkilian-na** [NetAppDocs/ontap-sanhost#190]
### Page URL

https://docs.netapp.com/us-en/ontap-sanhost/nvme_rhel_92.html

### Page title

NVMe-oF host configuration for RHEL 9.2 with ONTAP

### Summary

NVMe-FC namespaces mounted persistently through `/etc/fstab` cause RHEL 9.2 to fail to boot due to a known bug documented by Red Hat:
https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/9.2_release_notes/known-issues#known-issues-file-systems-and-storage 
"System fails to boot when adding an NVMe-FC device as a mount point in `/etc/fstab`"
Bugzilla:2168603

This may be worth adding to our known issues section, as there has been a support case for it. Issue was seen with `nvme-cli-2.2.1-2.el9.x86_64` and resolved by upgrading to `nvme-cli-2.4-10.el9.x86_64`. I am not sure exactly which nvme-cli versions are affected/fixed.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @kkilian-na, thank you for your recommendation. I will consult with the Engineers and update you here.
