### ISSUE TITLE
Missing necessary VIB install

### ISSUE THREAD

**Issue by jscott0918** [NetAppDocs/ontap-sanhost#38]
Page: [NVMe/FC Host Configuration for ESXi 7.0 with ONTAP](https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_7.html)

There is an additional bundle that should be installed, just installing the mentioned bundle actually will remove the NVMe HBAs from vcenter and esxcli outputs.

The bundle is named along the lines of: Emulex-NVMe-Transport-FC

The latest supported bundle should be included int his guide.

**Comment by netapp-aherbin** [comment]
Thank you for your comment.  We are investigating.
