### ISSUE TITLE
Typo in sidebar entry

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap-sanhost#39]
Page: [Linux Unified Host Utilities 7.1](https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html)

![image](https://user-images.githubusercontent.com/36739591/115706798-07d99f80-a33c-11eb-8a54-69c673ad11ec.png)

**Comment by netapp-aherbin** [comment]
Thank you Adam,

This issue has been fixed.
