### ISSUE TITLE
Hierarchy/sequence of sidebar items should follow a pattern

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap-sanhost#40]
Page: [NVMe/FC Host Configuration for RHEL 8.3 with ONTAP](https://docs.netapp.com/us-en/ontap-sanhost/nvme_rhel_83.html)

1. When we list multiple versions in the sidebar, the latest version should be the first. In the screenshot, this means 8.3 should be at the top of the RHEL section.
2. Check all the entries under each of the operating systems to ensure the "latest version first" pattern is followed.
3. The operating systems themselves should be listed in alphabetical order. In the screenshot below, that means "ESXi" should be at the top.

![image](https://user-images.githubusercontent.com/36739591/115707669-14122c80-a33d-11eb-922d-052fcc03bcd9.png)

**Comment by netapp-aherbin** [comment]
Thank you Adam,

The host operating systems have been listed in alphabetical order and the latest version now appears first under each one.

Amanda
