### ISSUE TITLE
Notice file linked to linux host utilities documentation needs verification

### ISSUE THREAD

**Issue by carun-netapp** [NetAppDocs/ontap-sanhost#54]
Page: [Linux Unified Host Utilities 7.1](https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html)

**Comment by carun-netapp** [comment]
Notice file linked to Linux Unified Host Utilities 7.1 has content referring to windows operating system.

**Comment by netapp-satyajit** [comment]
The Linux Unified Host Utilities uses the component “Microsoft Windows Server 2003 SP1 DDK” and hence you see that component in the NOTICE file.
