### ISSUE TITLE
hardware_handler

### ISSUE THREAD

**Issue by Brandon12345678901** [NetAppDocs/ontap-sanhost#65]
Page: [Using Red Hat Enterprise Linux 7.1 with NetApp ONTAP](https://docs.netapp.com/us-en/ontap-sanhost/hu_rhel_71.html)

In the table following this statement  "The table below shows the critical multipathd parameters for ONTAP LUNs and the required values". 

Speaking with my EE hardware handler should be hardware_handler "1 alua"  .

**Comment by netapp-ranuk** [comment]
Thanks for your comment. We're investigating this.

**Comment by netapp-ranuk** [comment]
Hi @Brandon12345678901 

Thanks for reaching out. We discussed the issue with the SMEs internally. Is it possible to contact you via email?

**Comment by netapp-ranuk** [comment]
Hi @Brandon12345678901 
Much of the multipath settings for NetApp are already hardcoded in the Linux libraries, based on the values referenced in the HU documentation.  Hence, we recommend an empty multipath file, unless you wish to change a parameter explicitly. Please let us know if you've further concerns.
