### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap-sanhost#66]
Page: [ONTAP SAN Host Configuration](https://docs.netapp.com/us-en/ontap-sanhost/index.html)

You can find additional information on SAN configurations in the following documentation:

[All SAN Array Software Configuration Guide](https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-asa-config/home.html)

=> Link broken...

**Comment by netapp-forry** [comment]
Thanks very much for letting us know. The correct link in the new doc site is:
https://docs.netapp.com/us-en/ontap/task_asa_software_configuration.html
We'll update the link ASAP.

**Comment by netapp-ranuk** [comment]
This issue has been fixed, thank you.
