### ISSUE TITLE
sd.conf and HUK bug

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap-sanhost#79]
Page: [Using Solaris 11.4 with NetApp ONTAP](https://docs.netapp.com/us-en/ontap-sanhost/hu_solaris_114.html)

We have a bug in the host utilities that needs to be documented in Solaris Host section. I see the HUK itself hasn't been ported to docs.netapp.com. Is that planned, or do we need to get someone to update the old PDF?

**Comment by netapp-ranuk** [comment]
Hi @jfsinmsp 

Moving the Solaris HUK content to docs.netapp.com was a planned activity. Therefore, any additions/modifications will be done in GitHub docs only moving forward. Besides, we will be moving away from the old pdf docs on the NSS site soon.

Please let us know if you have any other concerns.

Thank you
