### ISSUE TITLE
Release notes missing

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/ontap-sanhost#80]
Page: [AIX Host Utilities 6.1](https://docs.netapp.com/us-en/ontap-sanhost/hu_aix_61.html)

Can we please have release notes for these Host utility software's? the last we can see in our support site is 6.0 for AIX.

**Comment by netapp-ranuk** [comment]
Hi @sabarig84 

We have published the [HP-UX](https://docs.netapp.com/us-en/ontap-sanhost/nvme_rhel_90.html) and [Solaris](https://docs.netapp.com/us-en/ontap-sanhost/hu_solaris_62_rn.html) Release Notes. Please have a look at the site and let us know if you've further concerns.
